
services:
  xttsapiserver:
    image: xttsapiserver
    env_file: .env
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "${HOST_PORT:-8020}:${CONTAINER_PORT:-8020}"
    volumes:
      - ../xtts_models:/app/xtts-server/models
      - ../speakers:/app/xtts-server/speakers
      - ../output:/app/xtts-server/output